image: tmaier/docker-compose:20.10

services:
  - docker:20.10.11-dind

variables:
  GITLAB_USER: gitlab-ci-token
  PROD_SERVER_IP: 154.91.170.133
  PROD_SERVER_USER: root
  PROD_IMAGE_APP_TAG: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA-prod
  PROD_NGINX_IMAGE_APP_TAG: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHORT_SHA-prod

.init_ssh: &init_ssh |
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  echo "$SSH_PROD_SERVER_PRIVATE_KEY" > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa

before_script:
  - docker info

stages:
  - bake
  - deploy

bake:
  stage: bake
  script:
    - docker login -u $GITLAB_USER -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "IMAGE_APP_TAG=$PROD_IMAGE_APP_TAG" >> .env
    - echo "NGINX_IMAGE_APP_TAG=$PROD_NGINX_IMAGE_APP_TAG" >> .env
    - echo "$ENV_PROD" > .env.prod
    - docker-compose build
    - docker-compose push
  only:
    - master

deploy-to-prod:
  stage: deploy
  before_script:
    - apk update && apk add gettext
  script:
    - *init_ssh
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo "$CI_REGISTRY_IMAGE"
    - echo "IMAGE_APP_TAG=$PROD_IMAGE_APP_TAG" >> .env
    - echo "NGINX_IMAGE_APP_TAG=$PROD_NGINX_IMAGE_APP_TAG" >> .env
    - echo "$ENV_PROD" > .env.prod
    - export IMAGE_APP_TAG=$PROD_IMAGE_APP_TAG
    - export NGINX_IMAGE_APP_TAG=$PROD_NGINX_IMAGE_APP_TAG
    - envsubst < docker-compose.prod.yml > docker-compose.deployment.yml
    - scp -i ~/.ssh/id_rsa ./docker-compose.deployment.yml $PROD_SERVER_USER@$PROD_SERVER_IP:~/docker-compose.front.yml
    - scp -i ~/.ssh/id_rsa .env.prod $PROD_SERVER_USER@$PROD_SERVER_IP:~/.env.prod
    - ssh -i ~/.ssh/id_rsa -tt $PROD_SERVER_USER@$PROD_SERVER_IP "sudo docker logout $REGISTRY &&
      sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE &&
      sudo docker-compose -f docker-compose.front.yml pull &&
      sudo docker-compose -f docker-compose.front.yml -p front-end up -d &&
      sudo docker logout $REGISTRY"
  only:
    - master

