version: "3"

services:
  nuxt:
    image: ${IMAGE_APP_TAG}
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    command:
      "npm run start"

  nginx:
    image: ${NGINX_IMAGE_APP_TAG}
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - nuxt
