version: "3"

services:
  nuxt:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    command:
      "npm run start"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - nuxt
